#mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.110.128:3306/design?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8888
